name: Compile C++
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: hello.cpp
        run: g++ hello.cpp -o hello
      - name: Run program 
        run: ./hello

      - name: Compile calculator.cpp
        run: g++ calculator.cpp -o calculator
      - name: Run calculator 
        run: ./calculator
